/**
 * DO NOT CHANGE THIS FILE!
 * This file is automatically generated.
 */
import { ISysUserProfile } from "../dbtypes";
import { sql_insert, sql_query, sql_update, sql_delete } from "@blendsdk/sqlkit";
/**
 * Insert a record into the sys_user_profile relation
 */
export const insertIntoSysUserProfile = sql_insert<ISysUserProfile, ISysUserProfile>("sys_user_profile");
/**
 * Interface describing a getSysUserProfileByUserProfileId record.
 *
 * @interface IGetSysUserProfileByUserProfileId
 * @export
 */
export interface IGetSysUserProfileByUserProfileId {
	user_profile_id?: number;
}

/**
 * Gets a record from the sys_user_profile relation
 */
export const getSysUserProfileByUserProfileId = sql_query<ISysUserProfile, IGetSysUserProfileByUserProfileId>("SELECT * FROM sys_user_profile WHERE user_profile_id = :user_profile_id", { single: true });
/**
 * Interface describing a updateSysUserProfileByUserProfileId record.
 *
 * @interface IUpdateSysUserProfileByUserProfileId
 * @export
 */
export interface IUpdateSysUserProfileByUserProfileId {
	user_profile_id?: number;
}

/**
 * Updates a record from the sys_user_profile relation
 */
export const updateSysUserProfileByUserProfileId = sql_update<ISysUserProfile, ISysUserProfile, IUpdateSysUserProfileByUserProfileId>("sys_user_profile", { single: true } );
/**
 * Interface describing a deleteSysUserProfileByUserProfileId record.
 *
 * @interface IDeleteSysUserProfileByUserProfileId
 * @export
 */
export interface IDeleteSysUserProfileByUserProfileId {
	user_profile_id?: number;
}

/**
 * Deletes a record from the sys_user_profile relation
 */
export const deleteSysUserProfileByUserProfileId = sql_delete<ISysUserProfile, IDeleteSysUserProfileByUserProfileId>("sys_user_profile", { single: true } );