/**
 * DO NOT CHANGE THIS FILE!
 * This file is automatically generated.
 */
import { ISysUserRole } from "../dbtypes";
import { sql_insert, sql_query, sql_update, sql_delete } from "@blendsdk/sqlkit";
/**
 * Insert a record into the sys_user_role relation
 */
export const insertIntoSysUserRole = sql_insert<ISysUserRole, ISysUserRole>("sys_user_role");
/**
 * Interface describing a getSysUserRoleByUserRoleId record.
 *
 * @interface IGetSysUserRoleByUserRoleId
 * @export
 */
export interface IGetSysUserRoleByUserRoleId {
	user_role_id?: number;
}

/**
 * Gets a record from the sys_user_role relation
 */
export const getSysUserRoleByUserRoleId = sql_query<ISysUserRole, IGetSysUserRoleByUserRoleId>("SELECT * FROM sys_user_role WHERE user_role_id = :user_role_id", { single: true });
/**
 * Interface describing a updateSysUserRoleByUserRoleId record.
 *
 * @interface IUpdateSysUserRoleByUserRoleId
 * @export
 */
export interface IUpdateSysUserRoleByUserRoleId {
	user_role_id?: number;
}

/**
 * Updates a record from the sys_user_role relation
 */
export const updateSysUserRoleByUserRoleId = sql_update<ISysUserRole, ISysUserRole, IUpdateSysUserRoleByUserRoleId>("sys_user_role", { single: true } );
/**
 * Interface describing a deleteSysUserRoleByUserRoleId record.
 *
 * @interface IDeleteSysUserRoleByUserRoleId
 * @export
 */
export interface IDeleteSysUserRoleByUserRoleId {
	user_role_id?: number;
}

/**
 * Deletes a record from the sys_user_role relation
 */
export const deleteSysUserRoleByUserRoleId = sql_delete<ISysUserRole, IDeleteSysUserRoleByUserRoleId>("sys_user_role", { single: true } );