/**
 * DO NOT CHANGE THIS FILE!
 * This file is automatically generated.
 */
import { ISysI18n } from "../dbtypes";
import { sql_insert, sql_query, sql_update, sql_delete } from "@blendsdk/sqlkit";
/**
 * Insert a record into the sys_i18n relation
 */
export const insertIntoSysI18n = sql_insert<ISysI18n, ISysI18n>("sys_i18n");
/**
 * Interface describing a getSysI18nById record.
 *
 * @interface IGetSysI18nById
 * @export
 */
export interface IGetSysI18nById {
	id?: number;
}

/**
 * Gets a record from the sys_i18n relation
 */
export const getSysI18nById = sql_query<ISysI18n, IGetSysI18nById>("SELECT * FROM sys_i18n WHERE id = :id", { single: true });
/**
 * Interface describing a updateSysI18nById record.
 *
 * @interface IUpdateSysI18nById
 * @export
 */
export interface IUpdateSysI18nById {
	id?: number;
}

/**
 * Updates a record from the sys_i18n relation
 */
export const updateSysI18nById = sql_update<ISysI18n, ISysI18n, IUpdateSysI18nById>("sys_i18n", { single: true } );
/**
 * Interface describing a deleteSysI18nById record.
 *
 * @interface IDeleteSysI18nById
 * @export
 */
export interface IDeleteSysI18nById {
	id?: number;
}

/**
 * Deletes a record from the sys_i18n relation
 */
export const deleteSysI18nById = sql_delete<ISysI18n, IDeleteSysI18nById>("sys_i18n", { single: true } );